# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import stackl_sdk
from api.services_api import ServicesApi  # noqa: E501
from stackl_sdk.rest import ApiException


class TestServicesApi(unittest.TestCase):
    """ServicesApi unit test stubs"""

    def setUp(self):
        self.api = api.services_api.ServicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_service(self):
        """Test case for delete_service

        Delete Service  # noqa: E501
        """
        pass

    def test_get_service_by_name(self):
        """Test case for get_service_by_name

        Get Service By Name  # noqa: E501
        """
        pass

    def test_get_services(self):
        """Test case for get_services

        Get Services  # noqa: E501
        """
        pass

    def test_post_service(self):
        """Test case for post_service

        Post Service  # noqa: E501
        """
        pass

    def test_put_service(self):
        """Test case for put_service

        Put Service  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
