# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x61gent.proto\"\xea\x01\n\x11\x41utomationMessage\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x31\n\ninvocation\x18\x02 \x01(\x0b\x32\x1d.AutomationMessage.Invocation\x1a\x91\x01\n\nInvocation\x12\r\n\x05image\x18\x01 \x01(\t\x12\x1d\n\x15infrastructure_target\x18\x02 \x01(\t\x12\x16\n\x0estack_instance\x18\x03 \x01(\t\x12\x0f\n\x07service\x18\x04 \x01(\t\x12\x1e\n\x16\x66unctional_requirement\x18\x05 \x01(\t\x12\x0c\n\x04tool\x18\x06 \x01(\t\"\xff\x01\n\x12\x41utomationResponse\x12?\n\x11\x61utomation_result\x18\x01 \x01(\x0b\x32$.AutomationResponse.AutomationResult\x1a\x86\x01\n\x10\x41utomationResult\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x1e\n\x16\x66unctional_requirement\x18\x02 \x01(\t\x12*\n\x06status\x18\x03 \x01(\x0e\x32\x1a.AutomationResponse.Status\x12\x15\n\rerror_message\x18\x04 \x01(\t\"\x1f\n\x06Status\x12\t\n\x05READY\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x32L\n\x0bStacklAgent\x12=\n\x10InvokeAutomation\x12\x12.AutomationMessage\x1a\x13.AutomationResponse\"\x00\x62\x06proto3'
)



_AUTOMATIONRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='AutomationResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='READY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=477,
  serialized_end=508,
)
_sym_db.RegisterEnumDescriptor(_AUTOMATIONRESPONSE_STATUS)


_AUTOMATIONMESSAGE_INVOCATION = _descriptor.Descriptor(
  name='Invocation',
  full_name='AutomationMessage.Invocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='AutomationMessage.Invocation.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='infrastructure_target', full_name='AutomationMessage.Invocation.infrastructure_target', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stack_instance', full_name='AutomationMessage.Invocation.stack_instance', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='AutomationMessage.Invocation.service', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='functional_requirement', full_name='AutomationMessage.Invocation.functional_requirement', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tool', full_name='AutomationMessage.Invocation.tool', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=250,
)

_AUTOMATIONMESSAGE = _descriptor.Descriptor(
  name='AutomationMessage',
  full_name='AutomationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='AutomationMessage.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='invocation', full_name='AutomationMessage.invocation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AUTOMATIONMESSAGE_INVOCATION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=250,
)


_AUTOMATIONRESPONSE_AUTOMATIONRESULT = _descriptor.Descriptor(
  name='AutomationResult',
  full_name='AutomationResponse.AutomationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service', full_name='AutomationResponse.AutomationResult.service', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='functional_requirement', full_name='AutomationResponse.AutomationResult.functional_requirement', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='AutomationResponse.AutomationResult.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='AutomationResponse.AutomationResult.error_message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=475,
)

_AUTOMATIONRESPONSE = _descriptor.Descriptor(
  name='AutomationResponse',
  full_name='AutomationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='automation_result', full_name='AutomationResponse.automation_result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AUTOMATIONRESPONSE_AUTOMATIONRESULT, ],
  enum_types=[
    _AUTOMATIONRESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=508,
)

_AUTOMATIONMESSAGE_INVOCATION.containing_type = _AUTOMATIONMESSAGE
_AUTOMATIONMESSAGE.fields_by_name['invocation'].message_type = _AUTOMATIONMESSAGE_INVOCATION
_AUTOMATIONRESPONSE_AUTOMATIONRESULT.fields_by_name['status'].enum_type = _AUTOMATIONRESPONSE_STATUS
_AUTOMATIONRESPONSE_AUTOMATIONRESULT.containing_type = _AUTOMATIONRESPONSE
_AUTOMATIONRESPONSE.fields_by_name['automation_result'].message_type = _AUTOMATIONRESPONSE_AUTOMATIONRESULT
_AUTOMATIONRESPONSE_STATUS.containing_type = _AUTOMATIONRESPONSE
DESCRIPTOR.message_types_by_name['AutomationMessage'] = _AUTOMATIONMESSAGE
DESCRIPTOR.message_types_by_name['AutomationResponse'] = _AUTOMATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AutomationMessage = _reflection.GeneratedProtocolMessageType('AutomationMessage', (_message.Message,), {

  'Invocation' : _reflection.GeneratedProtocolMessageType('Invocation', (_message.Message,), {
    'DESCRIPTOR' : _AUTOMATIONMESSAGE_INVOCATION,
    '__module__' : 'agent_pb2'
    # @@protoc_insertion_point(class_scope:AutomationMessage.Invocation)
    })
  ,
  'DESCRIPTOR' : _AUTOMATIONMESSAGE,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:AutomationMessage)
  })
_sym_db.RegisterMessage(AutomationMessage)
_sym_db.RegisterMessage(AutomationMessage.Invocation)

AutomationResponse = _reflection.GeneratedProtocolMessageType('AutomationResponse', (_message.Message,), {

  'AutomationResult' : _reflection.GeneratedProtocolMessageType('AutomationResult', (_message.Message,), {
    'DESCRIPTOR' : _AUTOMATIONRESPONSE_AUTOMATIONRESULT,
    '__module__' : 'agent_pb2'
    # @@protoc_insertion_point(class_scope:AutomationResponse.AutomationResult)
    })
  ,
  'DESCRIPTOR' : _AUTOMATIONRESPONSE,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:AutomationResponse)
  })
_sym_db.RegisterMessage(AutomationResponse)
_sym_db.RegisterMessage(AutomationResponse.AutomationResult)



_STACKLAGENT = _descriptor.ServiceDescriptor(
  name='StacklAgent',
  full_name='StacklAgent',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=510,
  serialized_end=586,
  methods=[
  _descriptor.MethodDescriptor(
    name='InvokeAutomation',
    full_name='StacklAgent.InvokeAutomation',
    index=0,
    containing_service=None,
    input_type=_AUTOMATIONMESSAGE,
    output_type=_AUTOMATIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STACKLAGENT)

DESCRIPTOR.services_by_name['StacklAgent'] = _STACKLAGENT

# @@protoc_insertion_point(module_scope)
