# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import stackl_sdk
from models.functional_requirement import FunctionalRequirement  # noqa: E501
from stackl_sdk.rest import ApiException


class TestFunctionalRequirement(unittest.TestCase):
    """FunctionalRequirement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFunctionalRequirement(self):
        """Test FunctionalRequirement"""
        # FIXME: construct object with mandatory attributes with example values
        # model = stackl_sdk.models.functional_requirement.FunctionalRequirement()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
