# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import stackl_sdk
from models.infrastructure_target import InfrastructureTarget  # noqa: E501
from stackl_sdk.rest import ApiException


class TestInfrastructureTarget(unittest.TestCase):
    """InfrastructureTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInfrastructureTarget(self):
        """Test InfrastructureTarget"""
        # FIXME: construct object with mandatory attributes with example values
        # model = stackl_sdk.models.infrastructure_target.InfrastructureTarget()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
