# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class StackApplicationTemplate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'services': 'list[str]',
        'extra_functional_requirements': 'object',
        'category': 'str',
        'type': 'str'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'services': 'services',
        'extra_functional_requirements': 'extra_functional_requirements',
        'category': 'category',
        'type': 'type'
    }

    def __init__(self, name=None, description='', services=None, extra_functional_requirements=None, category='configs', type='stack_application_template'):  # noqa: E501
        """StackApplicationTemplate - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._description = None
        self._services = None
        self._extra_functional_requirements = None
        self._category = None
        self._type = None
        self.discriminator = None
        self.name = name
        if description is not None:
            self.description = description
        self.services = services
        if extra_functional_requirements is not None:
            self.extra_functional_requirements = extra_functional_requirements
        if category is not None:
            self.category = category
        if type is not None:
            self.type = type

    @property
    def name(self):
        """Gets the name of this StackApplicationTemplate.  # noqa: E501


        :return: The name of this StackApplicationTemplate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this StackApplicationTemplate.


        :param name: The name of this StackApplicationTemplate.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this StackApplicationTemplate.  # noqa: E501


        :return: The description of this StackApplicationTemplate.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this StackApplicationTemplate.


        :param description: The description of this StackApplicationTemplate.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def services(self):
        """Gets the services of this StackApplicationTemplate.  # noqa: E501


        :return: The services of this StackApplicationTemplate.  # noqa: E501
        :rtype: list[str]
        """
        return self._services

    @services.setter
    def services(self, services):
        """Sets the services of this StackApplicationTemplate.


        :param services: The services of this StackApplicationTemplate.  # noqa: E501
        :type: list[str]
        """
        if services is None:
            raise ValueError("Invalid value for `services`, must not be `None`")  # noqa: E501

        self._services = services

    @property
    def extra_functional_requirements(self):
        """Gets the extra_functional_requirements of this StackApplicationTemplate.  # noqa: E501


        :return: The extra_functional_requirements of this StackApplicationTemplate.  # noqa: E501
        :rtype: object
        """
        return self._extra_functional_requirements

    @extra_functional_requirements.setter
    def extra_functional_requirements(self, extra_functional_requirements):
        """Sets the extra_functional_requirements of this StackApplicationTemplate.


        :param extra_functional_requirements: The extra_functional_requirements of this StackApplicationTemplate.  # noqa: E501
        :type: object
        """

        self._extra_functional_requirements = extra_functional_requirements

    @property
    def category(self):
        """Gets the category of this StackApplicationTemplate.  # noqa: E501


        :return: The category of this StackApplicationTemplate.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this StackApplicationTemplate.


        :param category: The category of this StackApplicationTemplate.  # noqa: E501
        :type: str
        """

        self._category = category

    @property
    def type(self):
        """Gets the type of this StackApplicationTemplate.  # noqa: E501


        :return: The type of this StackApplicationTemplate.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this StackApplicationTemplate.


        :param type: The type of this StackApplicationTemplate.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StackApplicationTemplate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StackApplicationTemplate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
