on:
  push:
    paths:
    - "**/*"

jobs:
  stackl-cli:
    name: "Python ${{ matrix.python-version }}-stackl-cli"
    runs-on: [ubuntu-18.04]
    env:
      USING_COVERAGE: '3.7'

    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install pylint==2.4.4
      - run: listf=$(find stackl/cli -name "*.py") && pylint $listf

  stackl-rest:
    name: "Python ${{ matrix.python-version }}-stackl-rest"
    runs-on: [ubuntu-18.04]
    env:
      USING_COVERAGE: '3.7'

    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python-version }}
          poetry_version: 1.0.9
          working_directory: ./stackl/rest
          args: install
      - name: run pylint
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python-version }}
          poetry_version: 1.0.9
          working_directory: ./stackl/rest
          args: run pylint rest

  stackl-worker:
    name: "Python ${{ matrix.python-version }}-stackl-worker"
    runs-on: [ubuntu-18.04]
    env:
      USING_COVERAGE: '3.7'

    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python-version }}
          poetry_version: 1.0.9
          working_directory: ./stackl/worker
          args: install
      - name: Run pylint
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python-version }}
          poetry_version: 1.0.9
          working_directory: ./stackl/worker
          args: run pylint worker

  stackl-agent:
    name: "Python ${{ matrix.python-version }}-stackl-agent"
    runs-on: [ubuntu-18.04]
    env:
      USING_COVERAGE: '3.7'

    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python-version }}
          poetry_version: 1.0.9
          working_directory: ./stackl/agent
          args: install
      - name: Run pylint
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python-version }}
          poetry_version: 1.0.9
          working_directory: ./stackl/agent
          args: run pylint agent

  stackl-job-broker:
    name: "Python ${{ matrix.python-version }}-stackl-job-broker"
    runs-on: [ubuntu-18.04]
    env:
      USING_COVERAGE: '3.7'

    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python-version }}
          poetry_version: 1.0.9
          working_directory: ./stackl/job_broker
          args: install
      - name: Run pylint
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python-version }}
          poetry_version: 1.0.9
          working_directory: ./stackl/job_broker
          args: run pylint job_broker