FROM tiangolo/uwsgi-nginx-flask:python3.6
RUN pip3 install flask_restplus flask_moment flask_bootstrap marshmallow marshmallow_enum redis flask-cors requests tornado websockets grpcio protobuf && \
    mkdir /etc/stackl_src 
COPY build/app/nginx.conf /etc/nginx/nginx.conf
# COPY src /etc/stackl_src
COPY src /app
COPY static /app/static
COPY templates /app/templates
COPY build/app/entrypoint.sh /entrypoint.sh
COPY build/app/start.sh /start.sh
RUN cd /app ; \
    chmod 777 /app/stackl_app.py ; rm -f /var/log/nginx/access.log ; \
    chmod -R 777 /var/log/ ; \
    touch /var/log/nginx/access.log ; \
    chmod 777 /var/log/nginx/access.log ; \
    mkdir -p /var/log/supervisor/ ;\
    chmod +x /start.sh ; \
    chmod +x /entrypoint.sh ;\
    cd /app/
# RUN  unset -v PYTHONPATH
ENV PYTHONPATH "${PYTHONPATH}:/usr/local/lib/python3.6/site-packages/"
ADD build/app/uwsgi.ini /app/uwsgi.ini
ADD build/app/confd_nginx.conf /etc/nginx/conf.d/nginx.conf
