#use alpine?
FROM python:3.7-slim-buster 
RUN pip3 install pydantic redis tornado requests websockets grpcio protobuf
RUN mkdir /opt/stackl
COPY . /opt/stackl
CMD ["python", "/opt/stackl/workers/worker.py"]
